function FZ_ = C220WheelLoadsFunction(in1,in2)
%C220WHEELLOADSFUNCTION
%    FZ_ = C220WHEELLOADSFUNCTION(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    29-May-2018 18:24:46

Dp = in1(8,:);
Dr = in1(9,:);
Dz_CG = in1(12,:);
T_f = in2(1,:);
T_r = in2(2,:);
Z_f = in2(5,:);
Z_r = in2(6,:);
b_f = in2(10,:);
b_r = in2(11,:);
h_CG = in2(7,:);
k_f = in2(8,:);
k_r = in2(9,:);
l_f = in2(3,:);
l_r = in2(4,:);
p = in1(2,:);
r = in1(3,:);
z_CG = in1(6,:);
t2 = cos(p);
t3 = cos(r);
t4 = sin(p);
t5 = sin(r);
t6 = Dp.*l_f.*t2;
t7 = Dp.*Z_f.*t3.*t4;
t8 = Dr.*Z_f.*t2.*t5;
t9 = Dp.*T_f.*t4.*t5.*(1.0./2.0);
t10 = Z_f.*t2.*t3;
t11 = T_f.*t2.*t5.*(1.0./2.0);
t12 = Dp.*l_r.*t2;
t13 = Dr.*T_r.*t2.*t3.*(1.0./2.0);
t14 = l_r.*t4;
t15 = Z_r.*t2.*t3;
t16 = T_r.*t2.*t5.*(1.0./2.0);
FZ_ = [-b_f.*(-Dz_CG+t6+t7+t8+t9-Dr.*T_f.*t2.*t3.*(1.0./2.0))+k_f.*(-Z_f+h_CG+t10+t11+z_CG-l_f.*t4),-k_f.*(Z_f-h_CG-t10+t11-z_CG+l_f.*t4)-b_f.*(-Dz_CG+t6+t7+t8-t9+Dr.*T_f.*t2.*t3.*(1.0./2.0)),k_r.*(-Z_r+h_CG+t14+t15+t16+z_CG)+b_r.*(Dz_CG+t12+t13-Dp.*T_r.*t4.*t5.*(1.0./2.0)-Dp.*Z_r.*t3.*t4-Dr.*Z_r.*t2.*t5),b_r.*(Dz_CG+t12-t13+Dp.*T_r.*t4.*t5.*(1.0./2.0)-Dp.*Z_r.*t3.*t4-Dr.*Z_r.*t2.*t5)+k_r.*(-Z_r+h_CG+t14+t15-t16+z_CG)];
