function CPV_ = ContactPointVelocitiesFunction(in1,in2)
%CONTACTPOINTVELOCITIESFUNCTION
%    CPV_ = CONTACTPOINTVELOCITIESFUNCTION(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    09-Jul-2018 13:09:34

Dx_CG = in1(16,:);
Dy = in1(13,:);
Dy_CG = in1(17,:);
delta_f = in1(7,:);
delta_r = in1(8,:);
l_f = in2(4,:);
l_r = in2(5,:);
t_f = in2(2,:);
t_r = in2(3,:);
y = in1(1,:);
t2 = cos(delta_f);
t3 = sin(delta_f);
t4 = cos(y);
t5 = sin(y);
t6 = t4.^2;
t7 = t5.^2;
t8 = t2.^2;
t9 = t3.^2;
t10 = t8+t9;
t11 = 1.0./t10;
t12 = t6+t7;
t13 = 1.0./t12;
t14 = Dx_CG.*t2.*t4.*2.0;
t15 = Dy_CG.*t2.*t5.*2.0;
t16 = Dy_CG.*t3.*t4.*2.0;
t17 = Dy.*l_f.*t3.*t6.*2.0;
t18 = Dy.*l_f.*t3.*t7.*2.0;
t19 = cos(delta_r);
t20 = sin(delta_r);
t21 = t19.^2;
t22 = t20.^2;
t23 = t21+t22;
t24 = 1.0./t23;
t25 = Dx_CG.*t5.*t20.*2.0;
t26 = Dy.*t6.*t19.*t_r;
t27 = Dy.*l_r.*t6.*t20.*2.0;
t28 = Dy.*t7.*t19.*t_r;
t29 = Dy.*l_r.*t7.*t20.*2.0;
t30 = Dy_CG.*t2.*t4.*2.0;
t31 = Dy.*l_f.*t2.*t6.*2.0;
t32 = Dy.*l_f.*t2.*t7.*2.0;
t33 = Dy.*t3.*t6.*t_f;
t34 = Dy.*t3.*t7.*t_f;
t35 = Dx_CG.*t5.*t19.*2.0;
t36 = Dx_CG.*t4.*t20.*2.0;
t37 = Dy_CG.*t5.*t20.*2.0;
t38 = Dy.*l_r.*t6.*t19.*2.0;
t39 = Dy.*l_r.*t7.*t19.*2.0;
CPV_ = reshape([t11.*t13.*(t14+t15+t16+t17+t18-Dx_CG.*t3.*t5.*2.0-Dy.*t2.*t6.*t_f-Dy.*t2.*t7.*t_f).*(1.0./2.0),t11.*t13.*(t30+t31+t32+t33+t34-Dx_CG.*t2.*t5.*2.0-Dx_CG.*t3.*t4.*2.0-Dy_CG.*t3.*t5.*2.0).*(1.0./2.0),0.0,t11.*t13.*(t14+t15+t16+t17+t18-Dx_CG.*t3.*t5.*2.0+Dy.*t2.*t6.*t_f+Dy.*t2.*t7.*t_f).*(1.0./2.0),t11.*t13.*(-t30-t31-t32+t33+t34+Dx_CG.*t2.*t5.*2.0+Dx_CG.*t3.*t4.*2.0+Dy_CG.*t3.*t5.*2.0).*(-1.0./2.0),0.0,t13.*t24.*(t25+t26+t27+t28+t29-Dx_CG.*t4.*t19.*2.0-Dy_CG.*t4.*t20.*2.0-Dy_CG.*t5.*t19.*2.0).*(-1.0./2.0),t13.*t24.*(t35+t36+t37+t38+t39-Dy_CG.*t4.*t19.*2.0-Dy.*t6.*t20.*t_r-Dy.*t7.*t20.*t_r).*(-1.0./2.0),0.0,t13.*t24.*(-t25+t26-t27+t28-t29+Dx_CG.*t4.*t19.*2.0+Dy_CG.*t4.*t20.*2.0+Dy_CG.*t5.*t19.*2.0).*(1.0./2.0),t13.*t24.*(t35+t36+t37+t38+t39-Dy_CG.*t4.*t19.*2.0+Dy.*t6.*t20.*t_r+Dy.*t7.*t20.*t_r).*(-1.0./2.0),0.0],[3,4]);
