function xdot_ = suspmodel(in1,in2,in3)
%SUSPMODEL
%    XDOT_ = SUSPMODEL(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    04-Jul-2018 21:03:03

Dr = in1(6,:);
Dy = in1(4,:);
Dz = in1(5,:);
FCG = in2(:,1);
FRC = in2(:,4);
FWL = in2(:,2);
FWR = in2(:,3);
I = in3(7,:);
b = in3(2,:);
g = in3(8,:);
h = in3(4,:);
k = in3(1,:);
l = in3(3,:);
m = in3(6,:);
r = in1(3,:);
s = in3(5,:);
z = in1(2,:);
t2 = 1.0./m;
t3 = cos(r);
t4 = sin(r);
t5 = s.^2;
t6 = t3.^2;
t7 = t6.*2.0;
t8 = t7-1.0;
t9 = h.^2;
t10 = l.^2;
t11 = t4.^2;
t12 = k.^2;
xdot_ = [Dy;Dz;Dr;t2.*(FCG+FRC+FWL+FWR);t2.*(Dz.*b.*-2.0+g.*m+k.*s.*2.0-k.*z.*2.0+h.*k.*t3+h.*k.*t4-g.*m.*t12.*2.0-k.*l.*t3.*(1.0./2.0)+k.*l.*t4.*(1.0./2.0)-k.*s.*t3-k.*s.*t4+Dr.*b.*h.*t3-Dr.*b.*h.*t4+Dr.*b.*l.*t3.*(1.0./2.0)+Dr.*b.*l.*t4.*(1.0./2.0)-Dr.*b.*s.*t3+Dr.*b.*s.*t4);(FWR.*(h.*t3+h.*t4-s.*t3-s.*t4)-FWL.*(l.*t3.*(1.0./2.0)-l.*t4.*(1.0./2.0))+k.*t3.*t5-k.*t4.*t5-k.*t5.*t8-k.*t8.*t9+k.*t8.*t10.*(1.0./4.0)+FRC.*t3.*(h-s)-h.*k.*s.*t3+h.*k.*s.*t4+h.*k.*s.*t8.*2.0-k.*l.*s.*t3.*(1.0./2.0)-k.*l.*s.*t4.*(1.0./2.0)+h.*k.*t3.*z-h.*k.*t4.*z+k.*l.*t3.*z.*(1.0./2.0)+k.*l.*t4.*z.*(1.0./2.0)-k.*s.*t3.*z+k.*s.*t4.*z+Dz.*b.*h.*t3-Dz.*b.*h.*t4+Dz.*b.*l.*t3.*(1.0./2.0)+Dz.*b.*l.*t4.*(1.0./2.0)-Dz.*b.*s.*t3+Dz.*b.*s.*t4-Dr.*b.*t5.*t6-Dr.*b.*t6.*t9-Dr.*b.*t5.*t11-Dr.*b.*t6.*t10.*(1.0./4.0)-Dr.*b.*t9.*t11-Dr.*b.*t10.*t11.*(1.0./4.0)+Dr.*b.*h.*s.*t6.*2.0+Dr.*b.*h.*s.*t11.*2.0+Dr.*b.*t3.*t4.*t5.*2.0+Dr.*b.*t3.*t4.*t9.*2.0-Dr.*b.*t3.*t4.*t10.*(1.0./2.0)+g.*h.*m.*t3.*t12-g.*h.*m.*t4.*t12+g.*l.*m.*t3.*t12.*(1.0./2.0)+g.*l.*m.*t4.*t12.*(1.0./2.0)-g.*m.*s.*t3.*t12+g.*m.*s.*t4.*t12-Dr.*b.*h.*s.*t3.*t4.*4.0)./I];
