function FZ_ = WheelLoadsFunction(in1,in2)
%WHEELLOADSFUNCTION
%    FZ_ = WHEELLOADSFUNCTION(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    09-Jul-2018 13:09:33

Dp = in1(14,:);
Dr = in1(15,:);
Dz_CG = in1(18,:);
b_f = in2(13,:);
h_CG = in2(8,:);
h_f = in2(24,:);
h_r = in2(25,:);
k_f = in2(11,:);
l_f = in2(4,:);
l_r = in2(5,:);
p = in1(2,:);
q_f = in2(6,:);
q_r = in2(7,:);
r = in1(3,:);
t_f = in2(2,:);
t_r = in2(3,:);
z_CG = in1(6,:);
t2 = cos(p);
t3 = cos(r);
t4 = sin(p);
t5 = sin(r);
t6 = h_CG-q_f;
t7 = Dp.*l_f.*t2;
t8 = Dp.*t4.*t5.*t_f.*(1.0./2.0);
t9 = Dp.*t3.*t4.*t6;
t10 = Dr.*t2.*t5.*t6;
t11 = t2.*t5.*t_f.*(1.0./2.0);
t12 = t2.*t3.*t6;
t13 = h_CG-q_r;
t14 = Dp.*l_r.*t2;
t15 = Dr.*t2.*t3.*t_r.*(1.0./2.0);
t16 = l_r.*t4;
t17 = t2.*t5.*t_r.*(1.0./2.0);
t18 = t2.*t3.*t13;
FZ_ = [k_f.*(h_f+t11+t12+z_CG-l_f.*t4)-b_f.*(-Dz_CG+t7+t8+t9+t10-Dr.*t2.*t3.*t_f.*(1.0./2.0)),k_f.*(h_f-t11+t12+z_CG-l_f.*t4)-b_f.*(-Dz_CG+t7-t8+t9+t10+Dr.*t2.*t3.*t_f.*(1.0./2.0)),b_f.*(Dz_CG+t14+t15-Dp.*t4.*t5.*t_r.*(1.0./2.0)-Dp.*t3.*t4.*t13-Dr.*t2.*t5.*t13)+k_f.*(h_r+t16+t17+t18+z_CG),b_f.*(Dz_CG+t14-t15+Dp.*t4.*t5.*t_r.*(1.0./2.0)-Dp.*t3.*t4.*t13-Dr.*t2.*t5.*t13)+k_f.*(h_r+t16-t17+t18+z_CG)];
